"""PMO FEEDBACK_AMENDMENT - deterministic core.

The one governed way an APPROVED Specs baseline may receive a
NON-SCOPE-CHANGING, NON-FUNCTIONAL correction that originates from a
canonical Feedback record, without a Change Request.

Three outcomes (never overlapping mutation mechanisms):

  NO_ARTIFACT_CHANGE       Feedback needs no Specs edit; the record is resolved,
                           Specs / approval / publication / version untouched.
  FEEDBACK_AMENDMENT       A wording-only correction, PROVEN structurally.
  CHANGE_REQUEST_REQUIRED  Anything else. Nothing is written, no CR is created.

Why this is safe (deterministic, not "the model says meaning is unchanged")
---------------------------------------------------------------------------
1. It starts only from a canonical Feedback Item already recorded in
   `docs/pmo/feedback/` (validated with feedback-governance-guard.py's own
   validators), classified, owned, evidenced, with the correction attested in
   the record's own text. A direct Specs edit followed by retroactive Feedback
   cannot satisfy this.
2. The candidate is GENERATED by this module from an exact before/after
   correction applied to ONE named target - never accepted as free-form text.
3. Only a closed set of line kinds may change (wording-eligible requirement
   fields, requirement titles, prose). Actors, Module, Source/Intent mappings,
   Permissions, Business Rules (fields AND table), Dependencies, integrations,
   status/applicability states, identifiers, every table and heading and the
   Document Control are PROTECTED: any change there is CHANGE_REQUEST_REQUIRED.
4. Inside an eligible line the change must pass `prove_wording_only`: the
   protected token sequence (numbers, identifiers, symbols, negations, modals,
   quantifiers, comparators) is identical, only capitalization / punctuation /
   articles / proven spelling fixes / declared terminology equivalence differ.
   Anything unprovable falls through to CHANGE_REQUEST_REQUIRED.
5. Terminology normalization is either a declared equivalence (P = Q, attested
   in the Feedback text, Q already used in the baseline, neither an actor or
   module name) or a UNIFORM RENAME of a term that is replaced everywhere
   (the whole document equals the original with P->Q, Q previously absent).
6. Versioning reuses the existing model (minor + 1, spec-generation Section
   10 / PMO-SPEC-007). Changed requirements get `Last Modified In` = the new
   version and `Change Source` = the Feedback Item id (Section 21.1); one new
   Change History row is appended. `Execution Authorized` becomes false: the
   amended bytes need a fresh PM approval through the existing recorder. The
   previous approval and the previous approved bytes are ARCHIVED (never
   altered); the previous publication receipt stays as history and can never
   satisfy the new version/hash (publication_evidence_core).

The transaction (`begin -> validate -> finalize`, `abort`) uses the same
marker pattern as the other Specs transactions; a failed amendment writes
nothing; finalize is all-or-nothing with rollback. Automatic progression:
never - approval and publication remain separate explicit actions.

Python 3, standard library only.
"""

from __future__ import annotations

import difflib
import importlib.util as _ilu
import json
import os
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

_HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(_HERE))

import intent_approval_core as iac  # noqa: E402
import specs_approval_core as sac  # noqa: E402
import change_request_incorporation_core as crc  # noqa: E402
import specs_structural_repair_core as src  # noqa: E402

specs_guard = src.specs_guard
_clean = iac._clean
read_text = iac.read_text


def _load_hook(name, filename):
    spec = _ilu.spec_from_file_location(name, str(_HERE.parent / "hooks" / filename))
    mod = _ilu.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


fb_guard = _load_hook("feedback_governance_guard_for_amendment", "feedback-governance-guard.py")

OPERATION = "FEEDBACK_AMENDMENT"
TRANSACTION_TYPE = "SPECS_FEEDBACK_AMENDMENT"
MARKER_RELPATH_PARTS = (".pmo", "specs-feedback-amendment-transaction.json")
SPECS_POSIX = sac.SPECS_POSIX
OUTCOMES = ("NO_ARTIFACT_CHANGE", "FEEDBACK_AMENDMENT", "CHANGE_REQUIRED_PLACEHOLDER")
NO_ARTIFACT_CHANGE = "NO_ARTIFACT_CHANGE"
FEEDBACK_AMENDMENT = "FEEDBACK_AMENDMENT"
CHANGE_REQUEST_REQUIRED = "CHANGE_REQUEST_REQUIRED"

MARKER_REQUIRED_FIELDS = (
    "transaction_type", "transaction_id", "project_id", "artifact", "operation",
    "feedback_item_id", "spec_version_before", "spec_version_after",
    "specs_hash_before", "correction", "reason", "started_at", "status",
)
OPEN_STATUSES = {"ACTIVE"}

# Feedback classifications that may lead to a Specs amendment / resolution.
AMENDABLE_CLASSIFICATIONS = ("BUG", "ENHANCEMENT", "SUGGESTION", "CLARIFICATION")
NO_CHANGE_CLASSIFICATIONS = ("DUPLICATE", "NOT_ACTIONABLE")
OPEN_ITEM_STATUSES = ("OPEN", "ACKNOWLEDGED", "IN_PROGRESS")

WORDING_LABELS = (
    "Title", "Requirement", "Trigger", "Preconditions", "Inputs", "Outputs",
    "Validation Rules", "Alternate / Exception Behavior", "Primary Behavior",
    "Acceptance Criteria", "Constraints", "State Transitions",
)

_BLOCK_HEADING_RE = re.compile(r"^###\s+((?:FR|NFR)-\d+)\s+[—–-]\s+(\S.*?)\s*$")
_ANY_HEADING_RE = re.compile(r"^#{1,6}\s")
_BLOCK_END_RE = re.compile(r"^(?:#{1,3}\s|---\s*$)")
_FIELD_LINE_RE = re.compile(r"^- \*\*([^*|]+?):\*\*[ \t]*(.*)$")
_LIST_ITEM_RE = re.compile(r"^[ \t]+(?:[-*+]|\d+[.)])[ \t]+")
_TOKEN_RE = re.compile(r"[A-Za-z0-9_À-ɏ]+(?:['’][A-Za-z]+)?|[^\w\s]", re.UNICODE)
_ID_TOKEN_RE = re.compile(r"^[A-Za-z]+-\d+")


def marker_abspath(root):
    return os.path.join(root, *MARKER_RELPATH_PARTS)


def _now_iso():
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def deny(code, message):
    return src.deny(code, message)


# --------------------------------------------------------------------------- #
# Wording-only proof
# --------------------------------------------------------------------------- #

_PROTECTED_WORDS = frozenset("""
not no never only must may shall should cannot can without except unless all any
each every either neither nor none at least most more less than before after
within between above below exactly minimum maximum min max and or if then when
while until once always both own other same different than per plus minus times
first last next previous over under up down from to into onto by via
""".split())
_ARTICLES = frozenset(("a", "an", "the"))
_PUNCT_OK = frozenset(",.;:!?()'\"‘’“”-–—")
KNOWN_TYPOS = {
    "recieve": "receive", "recieved": "received", "recieves": "receives",
    "teh": "the", "adress": "address", "occured": "occurred", "seperate": "separate",
    "definately": "definitely", "acknowlege": "acknowledge", "neccessary": "necessary",
    "sucessful": "successful", "succesful": "successful", "enviroment": "environment",
    "managment": "management", "existance": "existence", "refered": "referred",
    "accomodate": "accommodate", "persistant": "persistent", "transfered": "transferred",
    "reciept": "receipt", "dispatchor": "dispatcher", "untill": "until",
    "wich": "which", "thier": "their", "beleive": "believe", "occassion": "occasion",
    "paymnet": "payment", "cutomer": "customer", "custmer": "customer",
}


def _tokens(text):
    return _TOKEN_RE.findall(text or "")


def _is_protected(tok):
    t = tok.lower()
    if any(ch.isdigit() for ch in t) or "_" in t:
        return True
    if _ID_TOKEN_RE.match(tok):
        return True
    if t in _PROTECTED_WORDS:
        return True
    if len(tok) == 1 and not tok.isalnum() and tok not in _PUNCT_OK:
        return True  # symbols: = < > + * / % $ & | # @ ^ ~ \ ...
    return False


def _osa(a, b):
    """Optimal-string-alignment (Damerau) distance."""
    a, b = a.lower(), b.lower()
    d = [[0] * (len(b) + 1) for _ in range(len(a) + 1)]
    for i in range(len(a) + 1):
        d[i][0] = i
    for j in range(len(b) + 1):
        d[0][j] = j
    for i in range(1, len(a) + 1):
        for j in range(1, len(b) + 1):
            c = 0 if a[i - 1] == b[j - 1] else 1
            d[i][j] = min(d[i - 1][j] + 1, d[i][j - 1] + 1, d[i - 1][j - 1] + c)
            if i > 1 and j > 1 and a[i - 1] == b[j - 2] and a[i - 2] == b[j - 1]:
                d[i][j] = min(d[i][j], d[i - 2][j - 2] + 1)
    return d[len(a)][len(b)]


def _word_counts(text):
    counts = {}
    for w in re.findall(r"[A-Za-z]+", text or ""):
        counts[w.lower()] = counts.get(w.lower(), 0) + 1
    return counts


def prove_wording_only(before_line, after_line, baseline_text, entity_phrases=(),
                       equivalence=None):
    """(ok, reason). Deterministic proof that `after_line` differs from
    `before_line` by wording only. `baseline_text` is the WHOLE approved
    document (vocabulary evidence). `equivalence` = (P, Q) attested terminology
    equivalence or None."""
    if before_line == after_line:
        return False, "no change"
    tb, ta = _tokens(before_line), _tokens(after_line)
    sm = difflib.SequenceMatcher(a=tb, b=ta, autojunk=False)
    vocab = _word_counts(baseline_text)
    line_vocab = _word_counts(before_line)
    entities = {e.lower() for e in entity_phrases if e}
    for tag, i1, i2, j1, j2 in sm.get_opcodes():
        if tag == "equal":
            continue
        a_span, b_span = tb[i1:i2], ta[j1:j2]
        a_txt, b_txt = " ".join(a_span), " ".join(b_span)
        # pure punctuation / articles inserted or removed
        if all((t in _PUNCT_OK) or (t.lower() in _ARTICLES) for t in a_span + b_span):
            if tag in ("insert", "delete") or (
                    tag == "replace" and all((t in _PUNCT_OK) or t.lower() in _ARTICLES for t in a_span + b_span)):
                if tag == "replace" and any(t.lower() in _ARTICLES for t in a_span + b_span):
                    # article <-> article: case-only or a <-> an is grammar; a<->the is not
                    if not (len(a_span) == 1 and len(b_span) == 1
                            and (a_span[0].lower() == b_span[0].lower()
                                 or {a_span[0].lower(), b_span[0].lower()} == {"a", "an"})):
                        return False, "article replaced ('{}' -> '{}')".format(a_txt, b_txt)
                continue
        # declared terminology equivalence (whole differing span)
        if equivalence and a_txt == equivalence[0] and b_txt == equivalence[1]:
            if a_txt.lower() in entities or b_txt.lower() in entities:
                return False, "'{}'/'{}' is an actor/module name - renaming an entity is not wording".format(a_txt, b_txt)
            if any(_is_protected(t) for t in a_span + b_span):
                return False, "terminology equivalence touches protected tokens"
            others = baseline_text.replace(before_line, "")
            if not re.search(r"(?<![A-Za-z])" + re.escape(b_txt) + r"(?![A-Za-z])", others):
                return False, "'{}' is not already used elsewhere in the approved baseline".format(b_txt)
            continue
        if tag != "replace" or len(a_span) != len(b_span):
            return False, "words added/removed/rephrased ('{}' -> '{}')".format(a_txt, b_txt)
        for a, b in zip(a_span, b_span):
            if a == b:
                continue
            if a.lower() == b.lower():
                if _is_protected(a) and not any(ch.isdigit() for ch in a) and "_" in a:
                    return False, "protected token '{}' altered".format(a)
                continue  # capitalization only
            if _is_protected(a) or _is_protected(b):
                return False, "protected token changed ('{}' -> '{}')".format(a, b)
            if not (a.isalpha() and b.isalpha()):
                return False, "non-word replacement ('{}' -> '{}')".format(a, b)
            if a.lower() in entities or b.lower() in entities:
                return False, "entity name changed ('{}' -> '{}')".format(a, b)
            known = KNOWN_TYPOS.get(a.lower()) == b.lower()
            if not known:
                if len(a) < 4 or len(b) < 4:
                    return False, "'{}' -> '{}' is not a provable spelling fix".format(a, b)
                limit = 1 if max(len(a), len(b)) < 6 else 2
                if _osa(a, b) > limit:
                    return False, "'{}' -> '{}' differs by more than a typo".format(a, b)
                # a change in the word ending (plural / tense / agent: confirm ->
                # confirms, manager -> managed) can turn one real word into another;
                # only INTERIOR corrections are provable typo fixes.
                al, bl = a.lower(), b.lower()
                lcp = 0
                while lcp < min(len(al), len(bl)) and al[lcp] == bl[lcp]:
                    lcp += 1
                if lcp >= min(len(al), len(bl)) - 1:
                    return False, "'{}' -> '{}' changes the word ending, which can change meaning".format(a, b)
                misspelling_elsewhere = vocab.get(a.lower(), 0) - line_vocab.get(a.lower(), 0)
                if misspelling_elsewhere > 0 or line_vocab.get(a.lower(), 0) != vocab.get(a.lower(), 0):
                    return False, "'{}' is an existing word of the baseline, not a typo".format(a)
                if vocab.get(b.lower(), 0) < 1:
                    return False, "'{}' is not attested in the baseline".format(b)
    return True, None


# --------------------------------------------------------------------------- #
# Document line classification (closed set of amendable surfaces)
# --------------------------------------------------------------------------- #

def line_kinds(lines):
    """[kind] per line: DOC_CONTROL / HEADING / TABLE / BLOCK_TITLE /
    FIELD_TEXT:<label> / FIELD_PROTECTED:<label> / PROSE / BLANK / RULE."""
    kinds = []
    in_block = False
    in_dc = False
    label = None
    for line in lines:
        if not line.strip():
            kinds.append("BLANK"); label = None; continue
        if line.strip() == "---":
            kinds.append("RULE"); in_block = False; label = None; continue
        if _ANY_HEADING_RE.match(line):
            in_dc = bool(re.match(r"^#{1,6}\s+.*document control", line, re.I))
            if _BLOCK_HEADING_RE.match(line):
                in_block = True
                kinds.append("BLOCK_TITLE")
            else:
                in_block = False
                kinds.append("HEADING")
            label = None
            continue
        if line.lstrip().startswith("|"):
            kinds.append("TABLE"); continue
        if in_dc:
            kinds.append("DOC_CONTROL"); continue
        if in_block:
            m = _FIELD_LINE_RE.match(line)
            if m:
                label = m.group(1)
                kinds.append(("FIELD_TEXT:" if label in WORDING_LABELS else "FIELD_PROTECTED:") + label)
                continue
            if _LIST_ITEM_RE.match(line) and label:
                kinds.append(("FIELD_TEXT:" if label in WORDING_LABELS else "FIELD_PROTECTED:") + label)
                continue
            kinds.append("FIELD_PROTECTED:?")
            continue
        kinds.append("PROSE")
    return kinds


def entity_phrases(text):
    """Actor / module names and integration providers (protected terms)."""
    out = set()
    for m in re.finditer(r"(?m)^- \*\*Actor\(s\):\*\*[ \t]*(.+)$", text):
        for part in re.split(r",|\band\b", m.group(1)):
            p = part.strip().strip("*`")
            if p:
                out.add(p)
    for m in re.finditer(r"(?m)^- \*\*Module:\*\*[ \t]*(.+)$", text):
        val = m.group(1).strip().strip("*`")
        out.add(val)
        if "/" in val:
            out.add(val.rsplit("/", 1)[1].strip())
    return out


def blocks_of(lines):
    """[(start, end_exclusive, rid)] for FR/NFR blocks."""
    out, i = [], 0
    while i < len(lines):
        m = _BLOCK_HEADING_RE.match(lines[i])
        if m:
            j = i + 1
            while j < len(lines) and not _BLOCK_END_RE.match(lines[j]):
                j += 1
            out.append((i, j, m.group(1)))
            i = j
        else:
            i += 1
    return out


# --------------------------------------------------------------------------- #
# Canonical Feedback record
# --------------------------------------------------------------------------- #

def _item_fields(block):
    fields = {}
    for line in block.split("\n"):
        if line.strip().startswith("|"):
            cells = [c.strip() for c in line.strip().strip("|").split("|")]
            if len(cells) >= 3 and cells[0] not in ("Field", "---") and not set(cells[0]) <= set("-: "):
                fields[cells[0]] = cells[2]
    return fields


def load_feedback_record(root, item_id):
    """(record-dict, Decision-or-None). Validates the record with the Feedback
    guard's own validators; returns the parsed item plus its batch metadata."""
    if not fb_guard.ITEM_ID_RE.match(item_id or ""):
        return None, deny("PMO-FB-AMEND-001", "'{}' is not a canonical Feedback Item id (FB-YYYY-NNN-NNN).".format(item_id))
    batch_id = item_id.rsplit("-", 1)[0]
    bpath = os.path.join(root, "docs", "pmo", "feedback", "batches", batch_id + ".md")
    text = read_text(bpath)
    if text is None:
        return None, deny("PMO-FB-AMEND-001",
                          "no canonical Feedback record: {} does not exist - a Specs "
                          "amendment must start from a recorded Feedback item.".format(
                              "docs/pmo/feedback/batches/{}.md".format(batch_id)))
    d = fb_guard.validate_batch_content(text, root, batch_id)
    if d is not None and getattr(d, "decision", "deny") != "allow":
        code = getattr(d, "code", None)
        if code:
            return None, deny("PMO-FB-AMEND-002", "the Feedback batch is not valid ({}: {}).".format(code, d.message))
    blocks = dict(fb_guard.find_item_blocks(text))
    if item_id not in blocks:
        return None, deny("PMO-FB-AMEND-001", "Feedback item {} is not in batch {}.".format(item_id, batch_id))
    item = _item_fields(blocks[item_id])
    dc = fb_guard.field_map_from_table(*fb_guard.first_table(text))
    tracker = read_text(os.path.join(root, "docs", "pmo", "feedback", "feedback-tracker.md"))
    if tracker is None:
        return None, deny("PMO-FB-AMEND-002", "the Feedback Tracker does not exist.")
    td = fb_guard.validate_tracker_content(tracker, root)
    if td is not None and getattr(td, "code", None):
        return None, deny("PMO-FB-AMEND-002", "the Feedback Tracker is not valid ({}: {}).".format(td.code, td.message))
    th, trows = fb_guard.table_by_header_prefix(tracker, "Item ID")
    reg = [r for r in fb_guard.rows_as_dicts(th, trows) if r.get("Item ID", "").strip() == item_id]
    if not reg:
        return None, deny("PMO-FB-AMEND-002", "Feedback item {} is not registered in the Feedback Tracker.".format(item_id))
    return {"item_id": item_id, "batch_id": batch_id, "batch_path": bpath, "batch_text": text,
            "item": item, "batch_dc": dc, "tracker_row": reg[0]}, None


def validate_record_for_processing(rec, target_ref=None):
    """None or Decision. The record must be canonical, classified, owned,
    evidenced and still open."""
    it = rec["item"]
    for f in ("Original Feedback", "Normalized Interpretation", "Classification",
              "Classification Rationale", "Evidence / Source Reference", "Created Date",
              "Status", "Affected Artifact"):
        if not _clean(it.get(f)):
            return deny("PMO-FB-AMEND-003", "the Feedback item is missing required field '{}'.".format(f))
    if not _clean(rec["batch_dc"].get("Received By")) and not _clean(rec["batch_dc"].get("Created By")):
        return deny("PMO-FB-AMEND-003", "the Feedback batch has no PM ownership (Received By / Created By).")
    status = _clean(it["Status"]).upper()
    if status not in OPEN_ITEM_STATUSES:
        return deny("PMO-FB-AMEND-004", "Feedback item {} is already {} - it cannot start a new amendment.".format(rec["item_id"], status))
    if not re.search(r"spec", _clean(it["Affected Artifact"]), re.I):
        return deny("PMO-FB-AMEND-006", "Feedback item {} does not target the Specification (Affected Artifact: '{}').".format(rec["item_id"], it["Affected Artifact"]))
    return None


def _norm_ws(s):
    return re.sub(r"\s+", " ", s or "").strip().lower()


def _attested(rec, *phrases):
    """True when at least one of `phrases` appears in the record's own
    Original Feedback / Normalized Interpretation (evidence tie)."""
    hay = _norm_ws(rec["item"].get("Original Feedback", "") + " " + rec["item"].get("Normalized Interpretation", ""))
    return any(p and _norm_ws(p) in hay for p in phrases)


# --------------------------------------------------------------------------- #
# Candidate construction + classification
# --------------------------------------------------------------------------- #

def next_minor(version):
    m = re.match(r"^(\d+)\.(\d+)$", _clean(version))
    if not m:
        return None
    return "{}.{}".format(m.group(1), int(m.group(2)) + 1)


def _cr(reason):
    return {"outcome": CHANGE_REQUEST_REQUIRED, "reasons": [reason], "candidate": None, "changed_ids": []}


def apply_correction(text, correction):
    """(candidate_text, changed_line_indexes, Decision-like reason | None).
    Pure. `correction` = {"kind": "text", "target": "FR-018", "before": "...",
    "after": "...", "equivalence": ["P", "Q"]|None} or {"kind": "rename",
    "from": "P", "to": "Q"}."""
    lines = text.split("\n")
    kinds = line_kinds(lines)
    kind = correction.get("kind")
    if kind == "rename":
        p, q = correction.get("from"), correction.get("to")
        if not p or not q or p == q:
            return None, [], "a rename needs two different terms"
        rx = re.compile(r"(?<![A-Za-z0-9])" + re.escape(p) + r"(?![A-Za-z0-9])")
        if re.search(r"(?<![A-Za-z0-9])" + re.escape(q) + r"(?![A-Za-z0-9])", text):
            return None, [], "SUBSTANTIVE: '{}' already exists in the baseline - the rename would merge two terms".format(q)
        changed = []
        new = list(lines)
        for i, l in enumerate(lines):
            if rx.search(l):
                if kinds[i] in ("DOC_CONTROL", "HEADING"):
                    return None, [], "SUBSTANTIVE: '{}' occurs in a protected line ({})".format(p, kinds[i])
                if kinds[i] == "BLOCK_TITLE" or kinds[i] == "TABLE" or kinds[i] == "PROSE" \
                        or kinds[i].startswith(("FIELD_TEXT", "FIELD_PROTECTED")):
                    # identifiers can never be renamed
                    if _ID_TOKEN_RE.match(p):
                        return None, [], "SUBSTANTIVE: identifiers cannot be renamed"
                    new[i] = rx.sub(q, l)
                    changed.append(i)
        if not changed:
            return None, [], "'{}' does not occur in the baseline".format(p)
        return "\n".join(new), changed, None
    if kind != "text":
        return None, [], "unknown correction kind"
    target, before, after = correction.get("target"), correction.get("before"), correction.get("after")
    if not target or not before or after is None or before == after:
        return None, [], "a text correction needs a target, a 'before' and a different 'after'"
    if "\n" in before or "\n" in after:
        return None, [], "SUBSTANTIVE: a correction spanning several lines adds or removes content"
    if re.match(r"^(?:FR|NFR)-\d+$", target):
        rng = [(s, e) for s, e, rid in blocks_of(lines) if rid == target]
        if not rng:
            return None, [], "target {} does not exist".format(target)
        lo, hi = rng[0]
    elif target.startswith("section:"):
        name = target[len("section:"):].strip().lower()
        lo = hi = None
        for i, l in enumerate(lines):
            if _ANY_HEADING_RE.match(l) and name in l.lower():
                lo = i + 1
                hi = i + 1
                while hi < len(lines) and not _ANY_HEADING_RE.match(lines[hi]):
                    hi += 1
                break
        if lo is None:
            return None, [], "section '{}' does not exist".format(name)
    else:
        return None, [], "target must be a requirement id (FR-nnn / NFR-nnn) or 'section:<heading>'"
    hits = [i for i in range(lo, hi) if before in lines[i]]
    total = sum(lines[i].count(before) for i in hits)
    if total != 1:
        return None, [], "the 'before' text occurs {} times in {} (must be exactly once)".format(total, target)
    i = hits[0]
    new = list(lines)
    new[i] = lines[i].replace(before, after, 1)
    return "\n".join(new), [i], None


def classify_candidate(before_text, candidate, changed_idx, correction, rec_attested_equivalence=True):
    """(outcome, reasons). Every changed line must be an amendable kind AND
    pass the wording proof (text) / be a pure term substitution (rename)."""
    blines = before_text.split("\n")
    alines = candidate.split("\n")
    if len(blines) != len(alines):
        return CHANGE_REQUEST_REQUIRED, ["the correction changes the document structure"]
    kinds = line_kinds(blines)
    ents = entity_phrases(before_text)
    reasons = []
    if correction.get("kind") == "rename":
        p, q = correction["from"], correction["to"]
        rx = re.compile(r"(?<![A-Za-z0-9])" + re.escape(p) + r"(?![A-Za-z0-9])")
        if rx.search(candidate):
            return CHANGE_REQUEST_REQUIRED, ["'{}' would remain in the baseline - not a uniform rename".format(p)]
        if candidate != "\n".join(rx.sub(q, l) for l in blines):
            return CHANGE_REQUEST_REQUIRED, ["the rename is not a pure substitution"]
        if any(t.isdigit() or "_" in t or _ID_TOKEN_RE.match(t) or t.lower() in _PROTECTED_WORDS
               or (len(t) == 1 and not t.isalnum() and t not in _PUNCT_OK) for t in _tokens(p) + _tokens(q)):
            return CHANGE_REQUEST_REQUIRED, ["a rename cannot involve numbers, identifiers or logic words"]
        return FEEDBACK_AMENDMENT, ["uniform terminology rename '{}' -> '{}' ({} line(s))".format(p, q, len(changed_idx))]
    eq = correction.get("equivalence")
    eq = tuple(eq) if eq else None
    for i in changed_idx:
        k = kinds[i]
        if k in ("BLOCK_TITLE",):
            m1, m2 = _BLOCK_HEADING_RE.match(blines[i]), _BLOCK_HEADING_RE.match(alines[i])
            if not (m1 and m2 and m1.group(1) == m2.group(1)):
                return CHANGE_REQUEST_REQUIRED, ["the requirement identifier in a heading would change"]
            ok, why = prove_wording_only(m1.group(2), m2.group(2), before_text, ents, eq)
        elif k.startswith("FIELD_TEXT:") or k == "PROSE":
            ok, why = prove_wording_only(blines[i], alines[i], before_text, ents, eq)
        else:
            return CHANGE_REQUEST_REQUIRED, [
                "the change touches a protected part of the baseline ({}) - "
                "requirements, actors, mappings, rules, tables and headings cannot be "
                "changed by Feedback".format(k.replace("FIELD_PROTECTED:", "field '").rstrip() + ("'" if k.startswith("FIELD_PROTECTED:") else ""))]
        if not ok:
            return CHANGE_REQUEST_REQUIRED, [why]
        reasons.append("wording-only: " + (correction.get("before") or ""))
    return FEEDBACK_AMENDMENT, reasons or ["wording-only correction"]


def stamp_candidate(candidate, before_text, changed_idx, item_id, old_version, new_version, date_iso, summary):
    """Governed metadata for a successful amendment: version, execution
    authorization, per-changed-requirement Last Modified In / Change Source,
    one Change History row. Returns (text, changed_requirement_ids)."""
    lines = candidate.split("\n")
    blocks = blocks_of(lines)
    changed_ids = []
    for s, e, rid in blocks:
        if any(s <= i < e for i in changed_idx):
            changed_ids.append(rid)
            for j in range(s, e):
                m = _FIELD_LINE_RE.match(lines[j])
                if m and m.group(1) == "Last Modified In":
                    lines[j] = "- **Last Modified In:** {}".format(new_version)
                elif m and m.group(1) == "Change Source":
                    lines[j] = "- **Change Source:** {}".format(item_id)
    text = "\n".join(lines)
    text, ok1 = iac.set_doc_control_field(text, "Spec Version", new_version)
    text, ok2 = iac.set_doc_control_field(text, "Execution Authorized", "false") if ok1 else (None, False)
    if not (ok1 and ok2):
        return None, []
    ids = ", ".join(changed_ids) if changed_ids else "(document text)"
    row = "| {} | {} | {} | {} | {} | Pending PM approval (Feedback amendment) |".format(
        new_version, date_iso, item_id, ids, summary)
    out = text.rstrip("\n").split("\n")
    # append the row directly after the last row of the Change History table
    hm = [i for i, l in enumerate(out) if re.match(r"^#{1,6}\s+.*specification change history", l, re.I)]
    if not hm:
        return None, []
    i = hm[0] + 1
    while i < len(out) and not out[i].strip().startswith("|"):
        i += 1
    while i < len(out) and out[i].strip().startswith("|"):
        i += 1
    out.insert(i, row)
    return "\n".join(out) + "\n", changed_ids


def build_candidate(root, item_id, correction):
    """The single deterministic classification + candidate pipeline.
    Read-only. Returns a dict {outcome, reasons, candidate, changed_ids,
    version_before, version_after, record}."""
    rec, d = load_feedback_record(root, item_id)
    if d is not None:
        return {"outcome": None, "decision": d}
    d = validate_record_for_processing(rec)
    if d is not None:
        return {"outcome": None, "decision": d}
    cls = _clean(rec["item"]["Classification"]).upper()
    linked_cr = _clean(rec["item"].get("Related CR"))
    if linked_cr and linked_cr.lower() not in ("none", "n/a", "-"):
        r = _cr("the Feedback item is linked to Change Request {} - it follows the Change Request lifecycle".format(linked_cr))
        r["record"] = rec
        return r
    if not correction:
        if cls == "CHANGE_REQUEST":
            r = _cr("the Feedback item is classified CHANGE_REQUEST")
            r["record"] = rec
            return r
        return {"outcome": NO_ARTIFACT_CHANGE, "reasons": ["the Feedback needs no Specs change"],
                "candidate": None, "changed_ids": [], "record": rec}
    if cls == "CHANGE_REQUEST":
        r = _cr("the Feedback item is classified CHANGE_REQUEST - it follows the Change Request lifecycle")
        r["record"] = rec
        return r
    if cls in NO_CHANGE_CLASSIFICATIONS:
        return {"outcome": NO_ARTIFACT_CHANGE,
                "reasons": ["the Feedback is classified {} and asks for no Specs change".format(cls)],
                "candidate": None, "changed_ids": [], "record": rec}
    if cls not in AMENDABLE_CLASSIFICATIONS:
        r = _cr("Feedback classification '{}' is not amendable".format(cls)); r["record"] = rec
        return r

    specs_text = read_text(src.specs_abspath(root))
    if specs_text is None:
        return {"outcome": None, "decision": deny("PMO-FB-AMEND-007", "no canonical Specs artifact.")}
    meta = sac.parse_spec_doc_control(specs_text)
    version_before = _clean(meta.get("spec_version"))
    version_after = next_minor(version_before)
    if version_after is None:
        return {"outcome": None, "decision": deny("PMO-FB-AMEND-007", "Spec Version '{}' cannot be advanced by the existing minor+1 rule.".format(version_before))}

    # evidence tie: the correction must be attested by the Feedback record itself
    phrases = [correction.get("before"), correction.get("after"), correction.get("from"), correction.get("to")]
    if not _attested(rec, *phrases):
        return {"outcome": None, "decision": deny(
            "PMO-FB-AMEND-008",
            "the requested correction is not attested by the Feedback record's own text "
            "(Original Feedback / Normalized Interpretation) - a Specs edit cannot precede its Feedback.")}
    if correction.get("kind") == "text":
        tgt = correction.get("target") or ""
        affected = _clean(rec["item"].get("Affected Existing Requirement IDs"))
        if re.match(r"^(?:FR|NFR)-\d+$", tgt) and tgt not in affected:
            return {"outcome": None, "decision": deny(
                "PMO-FB-AMEND-009",
                "the correction targets {} but the Feedback item's Affected Existing Requirement IDs "
                "('{}') do not include it.".format(tgt, affected or "none"))}
    eq = correction.get("equivalence")
    if eq and not _attested(rec, eq[0], eq[1]):
        return {"outcome": None, "decision": deny(
            "PMO-FB-AMEND-008", "the terminology equivalence is not attested by the Feedback record.")}

    candidate, changed_idx, why = apply_correction(specs_text, correction)
    if candidate is None and (why or "").startswith("SUBSTANTIVE:"):
        return {"outcome": CHANGE_REQUEST_REQUIRED, "reasons": [why[len("SUBSTANTIVE:"):].strip()],
                "candidate": None, "changed_ids": [], "record": rec, "version_before": version_before}
    if candidate is None:
        return {"outcome": None, "decision": deny("PMO-FB-AMEND-010", "the correction cannot be applied deterministically: {}.".format(why))}
    outcome, reasons = classify_candidate(specs_text, candidate, changed_idx, correction)
    if outcome != FEEDBACK_AMENDMENT:
        return {"outcome": CHANGE_REQUEST_REQUIRED, "reasons": reasons, "candidate": None,
                "changed_ids": [], "record": rec, "version_before": version_before}
    summary = "Feedback amendment (wording only, no functional change): {}".format(
        _summary_of(correction))
    stamped, changed_ids = stamp_candidate(candidate, specs_text, changed_idx, item_id,
                                           version_before, version_after,
                                           datetime.now(timezone.utc).strftime("%Y-%m-%d"), summary)
    if stamped is None:
        return {"outcome": None, "decision": deny("PMO-FB-AMEND-011", "the governed metadata could not be located deterministically.")}
    return {"outcome": FEEDBACK_AMENDMENT, "reasons": reasons, "candidate": stamped,
            "changed_ids": changed_ids, "record": rec, "version_before": version_before,
            "version_after": version_after, "correction_line_indexes": changed_idx}


def _summary_of(c):
    if c.get("kind") == "rename":
        return "terminology '{}' -> '{}'".format(c["from"], c["to"])
    return "'{}' -> '{}' in {}".format(c["before"], c["after"], c["target"])


# --------------------------------------------------------------------------- #
# PM-facing messages (business language; engineering mode adds the detail)
# --------------------------------------------------------------------------- #

def pm_message(result, engineering=False):
    o = result.get("outcome")
    if o == FEEDBACK_AMENDMENT:
        msg = ("Feedback identified as a non-functional baseline correction. It can be processed as a "
               "Feedback Amendment. No scope or functional behavior changes were detected. Once "
               "processed, the amended Specs will need your approval again before it is published.")
    elif o == NO_ARTIFACT_CHANGE:
        msg = ("This Feedback does not require any change to the Specs. It can be recorded as "
               "resolved; the approved baseline and its publication are unaffected.")
    elif o == CHANGE_REQUEST_REQUIRED:
        msg = ("This request changes more than wording - it would alter approved project content "
               "(" + "; ".join(result.get("reasons") or []) + "). It needs a Change Request. "
               "No change was made and no Change Request was created.")
    else:
        d = result.get("decision")
        msg = "This Feedback cannot be processed yet: " + (d.message if d else "unknown reason")
    if engineering:
        d = result.get("decision")
        msg += "\n[engineering] outcome={} reasons={} decision={}".format(
            o, result.get("reasons"), (d.code + ": " + d.message) if d else None)
    return msg


# --------------------------------------------------------------------------- #
# Transaction: markers, begin gates, finalize, abort
# --------------------------------------------------------------------------- #

def parse_marker(text):
    try:
        data = json.loads(text)
    except Exception as exc:
        return None, "marker is not valid JSON: {}".format(exc)
    if not isinstance(data, dict):
        return None, "marker did not parse to an object."
    missing = [f for f in MARKER_REQUIRED_FIELDS if f not in data]
    if missing:
        return data, "marker is missing field(s): {}.".format(", ".join(missing))
    if data.get("transaction_type") != TRANSACTION_TYPE or data.get("operation") != OPERATION:
        return data, "marker is not a {} transaction.".format(OPERATION)
    if data.get("status") not in OPEN_STATUSES:
        return data, "marker status '{}' is not a recognised open state.".format(data.get("status"))
    return data, None


def marker_status(root):
    text = read_text(marker_abspath(root))
    if text is None:
        return "ABSENT", None, None
    data, err = parse_marker(text)
    if err is not None:
        return "INVALID", data, err
    cfg = src.load_project_config(root) or {}
    pid = _clean((cfg.get("project") or {}).get("id"))
    if pid and _clean(data.get("project_id")).upper() != pid.upper():
        return "WRONG_PROJECT", data, "marker project_id does not match project-config.yaml."
    return "OPEN", data, None


def approved_baseline_gate(root, specs_text):
    """None when the current Specs is a valid, approved baseline whose approval
    matches (the only state an amendment applies to)."""
    d = specs_guard.full_spec_validation(root, spec_text=specs_text)
    if d is not None:
        return deny("PMO-FB-AMEND-012", "the current Specs is not clean ({}: {}).".format(d.code, d.message))
    meta = sac.parse_spec_doc_control(specs_text)
    if _clean(meta.get("execution_authorized")).lower() != "true":
        return deny("PMO-FB-AMEND-012", "the Specs is not an approved baseline (Execution Authorized is not true) - pre-approval fixes use the pre-baseline mechanisms.")
    data, err = sac.load_specs_approval(root)
    if data is None or err is not None:
        return deny("PMO-FB-AMEND-012", "no valid Specs approval record: {}".format(err))
    err = sac.validate_specs_approval_matches(root, spec_version=meta.get("spec_version"))
    if err is not None:
        return deny("PMO-FB-AMEND-012", err)
    return None


def concurrency_gate(root):
    if crc.cr_marker_status(root)[0] == "OPEN":
        return deny("PMO-FB-AMEND-013", "a Change Request transaction is open.")
    if crc.feedback_marker_is_open(root):
        return deny("PMO-FB-AMEND-013", "a Feedback-management transaction is open.")
    for parts, name in ((src.STRUCTURAL_REPAIR_MARKER_RELPATH_PARTS, "structural repair"),
                        (src.SCHEMA_MIGRATION_MARKER_RELPATH_PARTS, "schema migration"),
                        ((".pmo", "specs-approval-transaction.json"), "Specs approval")):
        if os.path.exists(os.path.join(root, *parts)):
            return deny("PMO-FB-AMEND-013", "a {} transaction marker exists.".format(name))
    return None


def plan_transaction(root, item_id, correction, reason):
    """(plan, Decision|None, classification-result). Read-only."""
    reason = _clean(reason)
    if not reason:
        return None, deny("PMO-FB-AMEND-014", "a processing reason (PM approval to process) is required."), None
    specs_text = read_text(src.specs_abspath(root))
    if specs_text is None:
        return None, deny("PMO-FB-AMEND-007", "no canonical Specs artifact."), None
    g = approved_baseline_gate(root, specs_text)
    if g is not None:
        return None, g, None
    g = concurrency_gate(root)
    if g is not None:
        return None, g, None
    res = build_candidate(root, item_id, correction)
    if res.get("decision") is not None:
        return None, res["decision"], res
    if res["outcome"] != FEEDBACK_AMENDMENT:
        return None, None, res
    dv = specs_guard.full_spec_validation(root, spec_text=res["candidate"])
    if dv is not None:
        return None, deny("PMO-FB-AMEND-015",
                          "the amended Specs would fail validation ({}: {}) - nothing written.".format(dv.code, dv.message)), res
    cfg = src.load_project_config(root) or {}
    plan = {
        "project_id": _clean((cfg.get("project") or {}).get("id")),
        "feedback_item_id": item_id, "correction": correction, "reason": reason,
        "spec_version_before": res["version_before"], "spec_version_after": res["version_after"],
        "specs_hash_before": src.sha256_of_text(specs_text), "changed_ids": res["changed_ids"],
    }
    return plan, None, res


def build_marker_data(plan, transaction_id, started_at):
    return {
        "transaction_type": TRANSACTION_TYPE, "transaction_id": transaction_id,
        "project_id": plan["project_id"], "artifact": SPECS_POSIX, "operation": OPERATION,
        "feedback_item_id": plan["feedback_item_id"],
        "spec_version_before": plan["spec_version_before"],
        "spec_version_after": plan["spec_version_after"],
        "specs_hash_before": plan["specs_hash_before"], "correction": plan["correction"],
        "spec_version": plan["spec_version_before"],
        "reason": plan["reason"], "started_at": started_at, "status": "ACTIVE",
    }


def _resolve_item_in_batch(rec, note, date_iso):
    """New batch text with the item's Status -> RESOLVED, Last Updated, and a
    Resolution row; the original table structure is kept."""
    text = rec["batch_text"]
    item_id = rec["item_id"]
    blocks = fb_guard.find_item_blocks(text)
    block = dict(blocks)[item_id]
    lines = block.split("\n")
    out, saw_status = [], False
    for l in lines:
        if l.strip().startswith("|"):
            cells = [c.strip() for c in l.strip().strip("|").split("|")]
            if len(cells) >= 3 and cells[0] == "Status":
                l = "| Status | {} | RESOLVED |".format(cells[1]); saw_status = True
            elif len(cells) >= 3 and cells[0] == "Last Updated":
                l = "| Last Updated | {} | {} |".format(cells[1], date_iso)
        out.append(l)
    if not saw_status:
        return None
    # append the resolution note as its own row after the last table row
    last = max(i for i, l in enumerate(out) if l.strip().startswith("|"))
    out.insert(last + 1, "| Resolution | OPTIONAL | {} |".format(note.replace("|", "/")))
    return text.replace(block, "\n".join(out), 1)


def _resolve_item_in_tracker(root, item_id, date_iso):
    path = os.path.join(root, "docs", "pmo", "feedback", "feedback-tracker.md")
    text = read_text(path)
    th, trows = fb_guard.table_by_header_prefix(text, "Item ID")
    out = []
    for line in text.split("\n"):
        cells = [c.strip() for c in line.strip().strip("|").split("|")] if line.strip().startswith("|") else None
        if cells and cells and cells[0] == item_id and th:
            idx = {h: i for i, h in enumerate(th)}
            if "Status" in idx and "Last Updated" in idx and len(cells) == len(th):
                cells[idx["Status"]] = "RESOLVED"
                cells[idx["Last Updated"]] = date_iso
                line = "| " + " | ".join(cells) + " |"
        out.append(line)
    return path, "\n".join(out)


def _close_feedback(root, rec, note, date_iso):
    """(files-dict {path: text}, Decision|None) - validated with the Feedback
    guard's validators BEFORE anything is written."""
    new_batch = _resolve_item_in_batch(rec, note, date_iso)
    if new_batch is None:
        return None, deny("PMO-FB-AMEND-016", "the Feedback item's Status row could not be located.")
    tpath, new_tracker = _resolve_item_in_tracker(root, rec["item_id"], date_iso)
    # The Feedback guard's tracker check cross-reads the batch files ON DISK, so
    # validate the pair against a staged copy of the feedback tree - nothing is
    # written to the real project until both files are proven valid together.
    import shutil
    import tempfile
    stage = tempfile.mkdtemp(prefix="pmo-fb-stage-")
    try:
        shutil.copytree(os.path.join(root, "docs", "pmo", "feedback"),
                        os.path.join(stage, "docs", "pmo", "feedback"))
        os.makedirs(os.path.join(stage, ".pmo"), exist_ok=True)
        cfgp = os.path.join(root, ".pmo", "project-config.yaml")
        if os.path.isfile(cfgp):
            shutil.copyfile(cfgp, os.path.join(stage, ".pmo", "project-config.yaml"))
        crp = os.path.join(root, "docs", "pmo", "cr")
        if os.path.isdir(crp):
            shutil.copytree(crp, os.path.join(stage, "docs", "pmo", "cr"))
        rel_b = os.path.relpath(rec["batch_path"], root)
        with open(os.path.join(stage, rel_b), "w", encoding="utf-8") as fh:
            fh.write(new_batch)
        with open(os.path.join(stage, os.path.relpath(tpath, root)), "w", encoding="utf-8") as fh:
            fh.write(new_tracker)
        d = fb_guard.validate_batch_content(new_batch, stage, rec["batch_id"])
        if d is not None and getattr(d, "code", None):
            return None, deny("PMO-FB-AMEND-016", "the resolved batch would be invalid ({}: {}).".format(d.code, d.message))
        d = fb_guard.validate_tracker_content(new_tracker, stage)
        if d is not None and getattr(d, "code", None):
            return None, deny("PMO-FB-AMEND-016", "the resolved tracker would be invalid ({}: {}).".format(d.code, d.message))
    finally:
        shutil.rmtree(stage, ignore_errors=True)
    return {rec["batch_path"]: new_batch, tpath: new_tracker}, None


def _write_all(root, writes, removals=(), moves=()):
    """All-or-nothing: snapshot every touched path, apply, roll back on any
    error. writes {path: text}; moves [(src, dst)] (copy then remove src)."""
    snapshot = {}

    def snap(p):
        if p not in snapshot:
            snapshot[p] = open(p, "rb").read() if os.path.isfile(p) else None
    touched = list(writes) + list(removals) + [x for m in moves for x in m]
    for p in touched:
        snap(p)
    try:
        for p, t in writes.items():
            os.makedirs(os.path.dirname(p), exist_ok=True)
            src.write_text(p, t)
        for a, b in moves:
            os.makedirs(os.path.dirname(b), exist_ok=True)
            with open(a, "rb") as fh:
                data = fh.read()
            with open(b, "wb") as fh:
                fh.write(data)
            os.remove(a)
        for p in removals:
            if os.path.exists(p):
                os.remove(p)
    except Exception:
        for p, data in snapshot.items():
            try:
                if data is None:
                    if os.path.exists(p):
                        os.remove(p)
                else:
                    os.makedirs(os.path.dirname(p), exist_ok=True)
                    with open(p, "wb") as fh:
                        fh.write(data)
            except OSError:
                pass
        raise


def finalize_amendment(root, marker_data):
    """Re-derive everything from disk; write only when the complete result
    validates. Returns (report, Decision|None)."""
    try:
        plan, d, res = plan_transaction_for_finalize(root, marker_data)
        if d is not None:
            return None, d
        specs_path = src.specs_abspath(root)
        before = read_text(specs_path)
        if src.sha256_of_text(before) != marker_data.get("specs_hash_before"):
            return None, deny("PMO-FB-AMEND-017", "specs.md changed since the transaction began - refusing a moving target.")
        rec = res["record"]
        date_iso = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        note = "Incorporated into Specs v{} as a wording-only Feedback amendment ({}).".format(
            res["version_after"], _summary_of(marker_data["correction"]))
        files, d = _close_feedback(root, rec, note, date_iso)
        if d is not None:
            return None, d
        sha12 = marker_data["specs_hash_before"][:12]
        ver = marker_data["spec_version_before"]
        base_archive = os.path.join(root, ".pmo", "baselines", "specs-v{}-{}.md".format(ver, sha12))
        approval = sac.approval_abspath(root)
        approval_archive = os.path.join(root, ".pmo", "approvals", "history",
                                        "specs-approval-v{}-{}.yaml".format(ver, sha12))
        writes = {specs_path: res["candidate"], base_archive: before}
        writes.update(files)
        moves = [(approval, approval_archive)]
        _write_all(root, writes, removals=[marker_abspath(root)], moves=moves)
        return {"feedback_item_id": marker_data["feedback_item_id"],
                "spec_version_before": ver, "spec_version_after": res["version_after"],
                "changed_requirements": res["changed_ids"],
                "previous_baseline_archive": base_archive,
                "previous_approval_archive": approval_archive,
                "reapproval_required": True, "publication_required_after_approval": True}, None
    except Exception as exc:  # pragma: no cover - fail closed
        return None, deny("PMO-FB-AMEND-999", "internal error during finalize: {}".format(exc))


def plan_transaction_for_finalize(root, marker_data):
    """Like plan_transaction, but the marker (not a CLI arg) supplies inputs
    and its own marker file is not a concurrency conflict."""
    saved = marker_abspath(root)
    text = read_text(saved)
    try:
        os.remove(saved)  # never let our own marker trip the gate
        return plan_transaction(root, marker_data["feedback_item_id"], marker_data["correction"], marker_data["reason"])
    finally:
        if text is not None and not os.path.exists(saved):
            with open(saved, "w", encoding="utf-8") as fh:
                fh.write(text)


def abort_transaction(root, marker_data, abort_reason):
    """Governed recovery for a transaction that did not finalize (marker only;
    hash-verified; never touches specs.md, approval, feedback)."""
    return src.abort_transaction(root, marker_data, abort_reason, marker_path=marker_abspath(root))


# --------------------------------------------------------------------------- #
# NO_ARTIFACT_CHANGE resolution (independent of any Specs mutation)
# --------------------------------------------------------------------------- #

def resolve_without_change(root, item_id, reason):
    """(report, Decision|None). Resolves the Feedback record; Specs, approval,
    publication and version are not touched."""
    reason = _clean(reason)
    if not reason:
        return None, deny("PMO-FB-AMEND-014", "a reason is required.")
    res = build_candidate(root, item_id, None)
    if res.get("decision") is not None:
        return None, res["decision"]
    if res["outcome"] != NO_ARTIFACT_CHANGE:
        return None, deny("PMO-FB-AMEND-018", "the Feedback item is classified CHANGE_REQUEST and follows the Change Request lifecycle.")
    g = concurrency_gate(root)
    if g is not None:
        return None, g
    date_iso = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    files, d = _close_feedback(root, res["record"], "Resolved with no Specs change: {}".format(reason), date_iso)
    if d is not None:
        return None, d
    _write_all(root, files)
    return {"feedback_item_id": item_id, "specs_changed": False}, None
